sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then
      pip install virtualenv==15.2.0;
      pip install tox==3.1.2;
    fi
  - pip install tox-travis
script:
  - tox
